//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertiseWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CritCompare
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CritCompare()
        {
            this.CritCompareCrit = new HashSet<CritCompareCrit>();
        }
    
        public int id_compare { get; set; }
        public int id_expertise { get; set; }
        public int id_expert { get; set; }
        public double mark_compare { get; set; }
    
        public virtual Expertises Expertises { get; set; }
        public virtual Experts Experts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CritCompareCrit> CritCompareCrit { get; set; }
    }
}
