

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ExpertiseWCFService
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class db_AAZEntities : DbContext
{
    public db_AAZEntities()
        : base("name=db_AAZEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Authors> Authors { get; set; }

    public virtual DbSet<CatCrit> CatCrit { get; set; }

    public virtual DbSet<Categories> Categories { get; set; }

    public virtual DbSet<Criterions> Criterions { get; set; }

    public virtual DbSet<CritValues> CritValues { get; set; }

    public virtual DbSet<ExpCrit> ExpCrit { get; set; }

    public virtual DbSet<ExpertFos> ExpertFos { get; set; }

    public virtual DbSet<ExpertiseMark> ExpertiseMark { get; set; }

    public virtual DbSet<Expertises> Expertises { get; set; }

    public virtual DbSet<Experts> Experts { get; set; }

    public virtual DbSet<FiledsOfScience> FiledsOfScience { get; set; }

    public virtual DbSet<Filmes> Filmes { get; set; }

    public virtual DbSet<FilmGenre> FilmGenre { get; set; }

    public virtual DbSet<Genrs> Genrs { get; set; }

    public virtual DbSet<GRNTI> GRNTI { get; set; }

    public virtual DbSet<Logs> Logs { get; set; }

    public virtual DbSet<Marks> Marks { get; set; }

    public virtual DbSet<ProjectAuthors> ProjectAuthors { get; set; }

    public virtual DbSet<ProjectExpertise> ProjectExpertise { get; set; }

    public virtual DbSet<ProjectFos> ProjectFos { get; set; }

    public virtual DbSet<Projects> Projects { get; set; }

    public virtual DbSet<RatedFilms> RatedFilms { get; set; }

    public virtual DbSet<RatedSerials> RatedSerials { get; set; }

    public virtual DbSet<Rights> Rights { get; set; }

    public virtual DbSet<Serials> Serials { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }

}

}

