//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertiseWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpertFos
    {
        public int id_expert_fos { get; set; }
        public int id_expert { get; set; }
        public int id_fos { get; set; }
    
        public virtual Experts Experts { get; set; }
        public virtual FiledsOfScience FiledsOfScience { get; set; }
    }
}
