//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertiseWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmGenre
    {
        public int id_film_genre { get; set; }
        public int id_film { get; set; }
        public int id_genre { get; set; }
    
        public virtual Filmes Filmes { get; set; }
        public virtual Genrs Genrs { get; set; }
    }
}
