//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertiseWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int log_id { get; set; }
        public System.DateTime log_date { get; set; }
        public string log_source { get; set; }
        public string log_message { get; set; }
        public string log_place { get; set; }
        public string log_param { get; set; }
    }
}
