//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertiseWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Marks()
        {
            this.ExpertiseMark = new HashSet<ExpertiseMark>();
        }
    
        public int id_mark { get; set; }
        public int id_expert { get; set; }
        public int id_crit { get; set; }
        public int id_project { get; set; }
        public int rating { get; set; }
    
        public virtual Criterions Criterions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpertiseMark> ExpertiseMark { get; set; }
        public virtual Experts Experts { get; set; }
    }
}
