//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertiseWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectFos
    {
        public int id_project_fos { get; set; }
        public int id_project { get; set; }
        public int id_fos { get; set; }
    
        public virtual FiledsOfScience FiledsOfScience { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
