
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ExpertiseWCFService
{

using System;
    using System.Collections.Generic;
    
public partial class ProjectAuthors
{

    public int id_proj_author { get; set; }

    public int id_proj { get; set; }

    public int id_author { get; set; }



    public virtual Authors Authors { get; set; }

    public virtual Projects Projects { get; set; }

}

}
