//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertiseWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projects()
        {
            this.ProjectAuthors = new HashSet<ProjectAuthors>();
            this.ProjectFos = new HashSet<ProjectFos>();
            this.ProjectExpertise = new HashSet<ProjectExpertise>();
        }
    
        public int id_project { get; set; }
        public string name_project { get; set; }
        public string lead_project { get; set; }
        public string grnti_project { get; set; }
        public System.DateTime begin_project { get; set; }
        public System.DateTime end_project { get; set; }
        public string money_project { get; set; }
        public string email_project { get; set; }
        public bool delete_project { get; set; }
        public bool exsist_exp_project { get; set; }
        public string org_project { get; set; }
    
        public virtual GRNTI GRNTI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectAuthors> ProjectAuthors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectFos> ProjectFos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectExpertise> ProjectExpertise { get; set; }
    }
}
